// Generated by BiTranspiler from MASM source
#include <iostream>
using namespace std;

int factorial(int n) {
    int eax = 0, ebx = 0, ecx = 0, edx = 0, ax = 0, bx = 0, cx = 0, dx = 0, al = 0, bl = 0, cl = 0, dl = 0; // CPU registers as variables
    int result;
    int i;
    result = 1;
    i = 1;
    while (i <= n) {
        result = (result * i);
        i = (i + 1);
    }
    eax = result;
    return eax;
    return eax;
}

int main() {
    int eax = 0, ebx = 0, ecx = 0, edx = 0, ax = 0, bx = 0, cx = 0, dx = 0, al = 0, bl = 0, cl = 0, dl = 0; // CPU registers as variables
    int num;
    int fact;
    num = 5;
    eax = num;
    fact = factorial(eax);
    eax = fact;
}

