; Generated by BiTranspiler
.386
.model flat, stdcall
.stack 4096
ExitProcess PROTO, dwExitCode:DWORD

.data

.code
fibonacci PROC n:DWORD
  LOCAL prev2:DWORD
  LOCAL prev1:DWORD
  LOCAL current:DWORD
  LOCAL i:DWORD
  mov eax, n
  cmp eax, 1
  setle al
  movzx eax, al
  cmp eax, 0
  je L_else_0
  mov eax, n
  ret
  jmp L_end_1
L_else_0:
L_end_1:
  mov eax, 0
  mov prev2, eax
  mov eax, 1
  mov prev1, eax
  mov eax, 0
  mov current, eax
  mov eax, 2
  mov i, eax
L_for_start_2:
  mov eax, i
  cmp eax, n
  setle al
  movzx eax, al
  cmp eax, 0
  je L_for_end_3
  mov eax, prev1
  add eax, prev2
  mov current, eax
  mov eax, prev1
  mov prev2, eax
  mov eax, current
  mov prev1, eax
  mov eax, i
  inc DWORD PTR [i]
  jmp L_for_start_2
L_for_end_3:
  mov eax, current
  ret
  ret
fibonacci ENDP

main PROC
  LOCAL val:DWORD
  mov eax, 7
  push eax
  call fibonacci
  mov val, eax
  mov eax, val
  invoke ExitProcess, eax
main ENDP

END main
