// Generated by BiTranspiler from MASM source
#include <iostream>
using namespace std;

int fibonacci(int n) {
    int eax = 0, ebx = 0, ecx = 0, edx = 0, ax = 0, bx = 0, cx = 0, dx = 0, al = 0, bl = 0, cl = 0, dl = 0; // CPU registers as variables
    int prev2;
    int prev1;
    int current;
    int i;
    eax = n;
    al = (eax <= 1);
    eax = al;
    if ((n <= 1) != 0) {
        eax = n;
        return eax;
    }
    prev2 = 0;
    prev1 = 1;
    current = 0;
    i = 2;
    while (i <= n) {
        current = (prev1 + prev2);
        prev2 = prev1;
        prev1 = current;
        eax = i;
        i = (i + 1);
    }
    eax = current;
    return eax;
    return eax;
}

int main() {
    int eax = 0, ebx = 0, ecx = 0, edx = 0, ax = 0, bx = 0, cx = 0, dx = 0, al = 0, bl = 0, cl = 0, dl = 0; // CPU registers as variables
    int val;
    eax = 7;
    val = fibonacci(eax);
    eax = val;
}

