; Generated by BiTranspiler
.386
.model flat, stdcall
.stack 4096
ExitProcess PROTO, dwExitCode:DWORD

.data

.code
factorial PROC n:DWORD
  LOCAL result:DWORD
  LOCAL i:DWORD
  mov eax, 1
  mov result, eax
  mov eax, 1
  mov i, eax
L_while_start_0:
  mov eax, i
  cmp eax, n
  setle al
  movzx eax, al
  cmp eax, 0
  je L_while_end_1
  mov eax, result
  imul eax, i
  mov result, eax
  mov eax, i
  add eax, 1
  mov i, eax
  jmp L_while_start_0
L_while_end_1:
  mov eax, result
  ret
  ret
factorial ENDP

main PROC
  LOCAL num:DWORD
  LOCAL fact:DWORD
  mov eax, 5
  mov num, eax
  mov eax, num
  push eax
  call factorial
  mov fact, eax
  mov eax, fact
  invoke ExitProcess, eax
main ENDP

END main
