; Generated by BiTranspiler
.386
.model flat, stdcall
.stack 4096
ExitProcess PROTO, dwExitCode:DWORD

.data

.code
main PROC
  LOCAL a:DWORD
  LOCAL b:DWORD
  LOCAL sum:DWORD
  LOCAL diff:DWORD
  LOCAL prod:DWORD
  LOCAL quot:DWORD
  mov eax, 10
  mov a, eax
  mov eax, 5
  mov b, eax
  mov eax, a
  add eax, b
  mov sum, eax
  mov eax, a
  sub eax, b
  mov diff, eax
  mov eax, a
  imul eax, b
  mov prod, eax
  mov eax, a
  mov ebx, b
  cdq
  idiv ebx
  mov quot, eax
  mov eax, sum
  invoke ExitProcess, eax
main ENDP

END main
