// Generated by BiTranspiler from MASM source
#include <iostream>
using namespace std;

int main() {
    int eax = 0, ebx = 0, ecx = 0, edx = 0, ax = 0, bx = 0, cx = 0, dx = 0, al = 0, bl = 0, cl = 0, dl = 0; // CPU registers as variables
    int a;
    int b;
    int sum;
    int diff;
    int prod;
    int quot;
    a = 10;
    b = 5;
    sum = (a + b);
    diff = (a - b);
    prod = (a * b);
    eax = a;
    ebx = b;
    eax = (eax / ebx);
    quot = eax;
    eax = sum;
}

